Add sqlite feature flag
maplibre/maplibre-rs pull request #111
Opened 2022-05-23 14:49 UTC by jackson211

Add "sqlite" feature flag to maplibre-build-tools.
However the maplibre still needs sqlite dependency, therefore the "sqlite" feature is still needed to be enabled in maplibre. Not sure if we need another flag in maplibre?

## 💻 Examples

## 🚨 Test instructions

## ✔️ PR Todo

- [x] Included links to related issues/PRs
#107

2022-05-23 15:02 UTC, maxammann requested changes

2022-05-23 15:02 UTC, maxammann commented on maplibre/Cargo.toml
> +maplibre-build-tools = { path = "../maplibre-build-tools", version = "0.1.0", features = ["sqlite"] }
I think we want to add a `embed-static-tiles` feature flag to `maplibre`.
That feature flag will enable the `sqlite` feature of the build-tools and conditionally embed tiles
 in the `build.rs` file.
Such that one can conditionally compile `maplibre`, once with sqlite support during building and once without.

2022-05-23 15:02 UTC, maxammann commented
I updated the branch because of major refactorings on `main`.

2022-05-23 15:30 UTC, jackson211 commented on maplibre-build-tools/src/mbtiles.rs
>  fn flip_vertical_axis(zoom: u8, value: u32) -> u32 {
Actually, I think we can remove dead_code flag for now as there are a lot of unfinished features.

2022-05-23 15:33 UTC, jackson211 commented
So, I have moved the `sqlite` flag from each function to the lib mod and added conditional flags in the `build.rs` file.

2022-05-25 17:41 UTC, maxammann approved these changes
This is fine! We can now think about removing the sqlite related code from the windows CI/CD pipeline

2022-05-25 17:49 UTC, maxammann commented
After buids finish I'd merge this :) thank you!

2022-05-26 09:27 UTC, merged