Feature raster tiles
maplibre/maplibre-rs pull request #141
Opened 2022-06-29 20:11 UTC by Quillasp

This is the first step of the raster tiles rendering feature #71. There's:

- Raster style layer from the [raster](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#raster) layer mapbox specification,
- Raster layer that will hold the raster data
- Two differents sources for vector tiles (Tessellate source) and raster source that will load different data following the layer type.

## 💻 Examples

## 🚨 Test instructions

## ✔️ PR Todo

- [x] Discussing how the different layer types should be fetched (one source client for the vector tiles and another one for the raster tiles? or fetching from the same source client with different address based on the layer type)
- [x] Raster data loading and storing
- [ ] Raster rendering

2022-06-30 07:59 UTC, ybiletskyi requested changes

2022-06-30 07:59 UTC, ybiletskyi commented on maplibre/src/io/tile_repository.rs
> +    pub fn is_layers_missing(
Probably rename to `missed_layers`. Clean up the commented code.

2022-06-30 07:59 UTC, ybiletskyi commented on maplibre/src/stages/request_stage.rs
> +                // let client = SourceClient::Http(self.http_source_client.clone());
Clean up commented code.

2022-06-30 07:59 UTC, ybiletskyi commented on maplibre/src/style/style.rs
> +                    paint: Some(LayerPaint::Raster(RasterLayer::default())),
`paint` should be `None`.

2022-06-30 07:59 UTC, ybiletskyi commented on maplibre/src/style/layer.rs
> +    #[serde(rename = "raster")]
Clean up this changes. We will not use `LayerPaint` for raster tiles.

2022-07-01 07:54 UTC, ybiletskyi commented on maplibre/src/style/layer.rs
Looks like changes in this file is not used. Please clean up.

2022-07-04 13:59 UTC, maxammann requested changes

2022-07-04 13:59 UTC, maxammann commented on maplibre-demo/src/main.rs
> +        );
This transformation should happen within the source client.

2022-07-04 13:59 UTC, maxammann commented on maplibre/src/io/source_client.rs
> +    pub async fn fetch(&self, url: &str) -> Result<Vec<u8>, Error> {
The previous interface should be kept. What was the reason for the change?

2022-07-04 13:59 UTC, maxammann commented on maplibre/src/stages/request_stage.rs
> +pub trait Source<SM, HC>
Source should not be part of the stages module

2022-07-04 13:59 UTC, maxammann commented on maplibre/src/stages/request_stage.rs
> +        request_stage: &RequestStage<SM, HC>,
A source should not depend on the RequestStage and vice-versa

2022-07-04 13:59 UTC, maxammann commented on maplibre/src/style/layer.rs
> +    Raster(RasterLayer),
A raster layer is not related to the color. The a raster layer should be another case for the `LayerPaint` enum.

2022-07-17 14:21 UTC, maxammann commented
@Quillasp I merged in main and fixed all conflicts

2022-11-07 09:48 UTC, maxammann commented
@Quillasp I would propose not to try to merge main into this PR, but manually check the relevant changes and then copy them to a new branch.
A lot has changed in the past months, so there will definitely be a lot of changes.

2022-11-14 22:03 UTC, maxammann commented
Closing in favor of #205

2022-11-14 22:03 UTC, closed without merging